### ISSUE TITLE
new features to add

### ISSUE THREAD

**Issue by fdiblen** [jiskattema/spot#17]
- [x] zoom functionality for charts
- [x] progress bar
- [x] better mobile device support

**Comment by jiskattema** [comment]
All chart that can select data now can zoom to the selection; more specifically: restrict their range to the selection, and re-bin. Zooming out also works. The 3d plot via plotly allows free 3d zooming, rotation, and panning without rebinning.
Open issue is showing a visual clue what points are selected on the linechart and the 3d plot.

**Comment by jiskattema** [comment]
We added a snackbar to the main page for user messages. Can be used via app.message(). Notifications for uploading and scanning are implemented; not what else is needed.

**Comment by jiskattema** [comment]
Mobile device support will come when we rewrite the analyze page for better drag and drop support via some external library. Probably interact.js
