### ISSUE TITLE
drag & drop improvement

### ISSUE THREAD

**Issue by fdiblen** [jiskattema/spot#22]
Drag and drop needs to be improved.

http://interactjs.io looks like a good option.

**Comment by fdiblen** [comment]
Another option is to use MD chips component.
https://material.google.com/components/chips.html

**Comment by fdiblen** [comment]
Another good option which may hurt a bit :)

https://github.com/bevacqua/dragula

**Comment by jiskattema** [comment]
Now using [SortableJS](http://rubaxa.github.io/Sortable/) for drag and drop and sorted lists.
