### ISSUE TITLE
Requested Feature 

### ISSUE THREAD

**Issue by anandgavai** [jiskattema/spot#30]
Exploratory Analysis:
1. Still a network hairball chart is desirable before the following.

Downstream Analysis:
1. To add a summary statistics below the visualized analysis/triples. For example the most frequent Subject, Predicate and Object.

**Comment by jiskattema** [comment]
Can you give some more details? 
* A link to a hairball chart (png)
* we should add more statistics on screen; but i'm not sure what you mean here

**Comment by anandgavai** [comment]
Network Chart:

- [https://ideas.sap.com/ct/getfile.bix?a=OD5268&f=A4533989-CD60-4E7B-89C3-397254DF7979&c=6013C007-A70B-4283-93CE-2531683D816D]

- Summary stastistics for example 

1.  Frequency of each concept
2. Total concepts
3. Percentage

**Comment by jiskattema** [comment]
Ok, i see what kind of chart you want. Can you also show me some typical data structure (json, csv) file that should give such a chart? There are lots of ways to store networks..

**Comment by anandgavai** [comment]
At this moment it would be great if we have three columns separated by "," representing Subject, Predicate & Object. Please see an example [https://github.com/DTL-FAIRData/ODEX4all-UseCases/blob/master/DSM/triple/app/triple_comma2.csv]

**Comment by jiskattema** [comment]
ok, there is a first version of a hairball plot with force directed layout.
You can add 2 partitions, one for 'subject' and one for 'object'.
It is assumed that the objects and subjects are from the same set, ie. each object can be a subject and vice versa.

Ideas on how to go on from here welcome, fi:
* color the edges based on predicate
* color / shape / size the nodes based on another property
...

For the statistics, you can ofcourse add more plots, fi
 * one showing a histogram count by predicate
 * one showing a histogram of object, subdiveded by predicate
* ...

**Comment by anandgavai** [comment]
Great,would certainly like to explore it together with you or Faruk this thursday ?
